dxx-rebirth - fix building for arm on aarch64 kernel
Build fails due to useless-cast with -Werror=useless-cast set.

    similar/main/songs.cpp: In function ‘void d1x::songs_play_level_song(int, int)’:
    similar/main/songs.cpp:796:53: error: useless cast to type ‘unsigned int’ [-Werror=useless-cast]
      796 |                     const song_number secretsongnum{static_cast<unsigned>((-levelnum - 1) % size)};
          |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Patch removes the cast for arm targets with gcc 12.2.0 (May happen in other environments also)

Reported upstream https://github.com/dxx-rebirth/dxx-rebirth/issues/813